name: CI
on: [push]
jobs:
  backend-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Lint
        run: pre-commit run -a

  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m venv ${{ github.workspace }}/.venv
          source ${{ github.workspace }}/.venv/bin/activate
          python -m pip install --verbose --upgrade pip pipenv
          pipenv sync --verbose --dev
      - name: Run tests
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/.venv
          PATH: ${{ github.workspace }}/.venv/bin
          PIPENV_VERBOSITY: -1
        run: |
          export PYTHONPATH=${PYTHONPATH}:${{ github.workspace }}
          pipenv run tests
